include:
  - project: kaisensdata/devops/cicd-templates
    ref: master
    file:
      - templates/django-app.yml
      - addons/deploy-app.yml

variables:
  SVC_NAMES: django celeryworker celerybeat redis
  DEPLOY_REPO_PATH : kaisensdata/deployments/apps/4inshield/backend/dauthenticator
