version: '2.2'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django:
  
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: dauthenticator_local_django
    container_name: hr_dev_dauthenticator_django
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8022:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: hr_dev_dauthenticator_postgres
    container_name: postgres_da
    restart: unless-stopped
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

