#!/bin/bash
set -o errexit
# set -o pipefail
set -o nounset


python /app/manage.py collectstatic --noinput
python /app/manage.py migrate


compress_enabled() {
python << END
import sys

from environ import Env

env = Env(COMPRESS_ENABLED=(bool, True))
if env('COMPRESS_ENABLED'):
    sys.exit(0)
else:
    sys.exit(1)

END
}

if compress_enabled; then
  python /app/manage.py compress --force --follow-links --extension=EXTENSIONS
fi
gunicorn config.wsgi --preload --bind 0.0.0.0:8000 --access-logfile /app/logs/server_access.log --error-logfile /app/logs/server_errors.log --log-level debug --threads 4 --workers 4 --capture-output --chdir=/app
