# Generated by Django 3.1.12 on 2022-05-18 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAuthentification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.EmailField(max_length=256)),
                ('password', models.CharField(max_length=250)),
                ('user_id', models.CharField(max_length=250)),
                ('media', models.CharField(choices=[('twitter', 1), ('instagram', 2), ('tiktok', 3)], default='twitter', max_length=128)),
                ('active', models.BooleanField(default=True)),
                ('ip', models.CharField(max_length=128)),
                ('cookie', models.TextField(null=True)),
                ('cookie_valid', models.BooleanField(default=False)),
                ('cookie_start', models.DateTimeField(blank=True, null=True)),
                ('cookie_expected_end', models.DateTimeField(blank=True, null=True)),
                ('cookie_real_end', models.DateTimeField(blank=True, null=True)),
                ('account_active', models.BooleanField(default=False)),
                ('account_valid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AirflowDAGRUN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dag_run_id', models.CharField(max_length=256)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.accountauthentification')),
            ],
        ),
    ]
