# Generated by Django 3.1.12 on 2023-02-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230206_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='strategy',
            field=models.CharField(default='strategy1', max_length=256),
        ),
    ]
