# Generated by Django 3.1.12 on 2023-02-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_driver_strategy'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='accountauthentification',
            constraint=models.UniqueConstraint(fields=('user_id', 'media'), name='user_id_media_unique'),
        ),
    ]
