# Generated by Django 3.1.12 on 2023-03-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230207_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountauthentification',
            name='client_name',
            field=models.CharField(blank=True, default='crawlserver', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='accountauthentification',
            name='media',
            field=models.CharField(choices=[('twitter', 1), ('instagram', 2), ('facebook', 3), ('quora', 4), ('adoasis', 5)], default='twitter', max_length=128),
        ),
    ]
