# Generated by Django 3.1.12 on 2023-05-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230303_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountauthentification',
            name='media',
            field=models.CharField(choices=[('twitter', 1), ('instagram', 2), ('facebook', 3), ('quora', 4), ('adoasis', 5), ('tumblr', 6)], default='twitter', max_length=128),
        ),
    ]
