# Generated by Django 3.1.12 on 2023-09-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230803_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountauthentification',
            name='cookie',
            field=models.TextField(blank=True, null=True),
        ),
    ]
