# Generated by Django 3.2.15 on 2024-03-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20230907_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountauthentification',
            name='issue',
            field=models.TextField(blank=True, null=True),
        ),
    ]
