# Generated by Django 3.2.15 on 2024-05-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_accountauthentification_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountauthentification',
            name='consumption_time',
            field=models.IntegerField(default=0),
        ),
    ]
