#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python /app/manage.py collectstatic --noinput
python manage.py migrate

/usr/local/bin/gunicorn config.wsgi:application -c /app/compose/production/django/gunicorn.conf.py

